# Generated by Django 5.2.5 on 2025-11-21 13:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='producto',
            options={'ordering': ['orden', '-fecha_creacion'], 'verbose_name': 'Producto', 'verbose_name_plural': 'Productos'},
        ),
        migrations.AddField(
            model_name='producto',
            name='orden',
            field=models.IntegerField(default=0, help_text='Orden de visualización (menor número aparece primero)', verbose_name='Orden'),
        ),
        migrations.AddField(
            model_name='producto',
            name='precio',
            field=models.DecimalField(decimal_places=0, default=0, help_text='Precio en pesos chilenos', max_digits=10, verbose_name='Precio'),
            preserve_default=False,
        ),
    ]
