# Generated by Django 5.1.2 on 2025-11-22 22:18

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_completo', models.CharField(help_text='Nombre completo del cliente', max_length=200, verbose_name='Nombre Completo')),
                ('rut', models.CharField(help_text='RUT único del cliente (formato: 12.345.678-9)', max_length=12, unique=True, validators=[django.core.validators.RegexValidator(message='RUT debe estar en formato: 12.345.678-9', regex='^\\d{1,2}\\.\\d{3}\\.\\d{3}[-][0-9kK]{1}$|^\\d{7,8}[-][0-9kK]{1}$')], verbose_name='RUT')),
                ('email', models.EmailField(help_text='Email principal de contacto', max_length=254, verbose_name='Email')),
                ('telefono', models.CharField(blank=True, help_text='Teléfono de contacto', max_length=17, validators=[django.core.validators.RegexValidator(message="Número de teléfono debe estar en formato: '+999999999'. Hasta 15 dígitos.", regex='^\\+?1?\\d{9,15}$')], verbose_name='Teléfono')),
                ('direccion', models.CharField(blank=True, help_text='Dirección principal del cliente', max_length=300, verbose_name='Dirección')),
                ('empresa', models.CharField(blank=True, help_text='Nombre de la empresa (si es cliente corporativo)', max_length=200, verbose_name='Empresa')),
                ('descuento_habitual', models.DecimalField(decimal_places=2, default=0, help_text='Porcentaje de descuento por ser cliente recurrente (0-100)', max_digits=5, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='Descuento Habitual (%)')),
                ('notas', models.TextField(blank=True, help_text='Notas y observaciones internas sobre el cliente', verbose_name='Notas Internas')),
                ('activo', models.BooleanField(default=True, help_text='Indica si el cliente está activo en el sistema', verbose_name='Cliente Activo')),
                ('fecha_registro', models.DateTimeField(auto_now_add=True, help_text='Fecha en que se registró el cliente', verbose_name='Fecha de Registro')),
                ('ultima_actualizacion', models.DateTimeField(auto_now=True, help_text='Última vez que se modificó el registro', verbose_name='Última Actualización')),
                ('ultima_cotizacion', models.DateTimeField(blank=True, help_text='Fecha de la última cotización realizada para este cliente', null=True, verbose_name='Última Cotización')),
            ],
            options={
                'verbose_name': 'Cliente',
                'verbose_name_plural': 'Clientes',
                'ordering': ['-ultima_cotizacion', '-fecha_registro'],
                'indexes': [models.Index(fields=['rut'], name='clientes_cl_rut_43a54a_idx'), models.Index(fields=['email'], name='clientes_cl_email_eae461_idx'), models.Index(fields=['-ultima_cotizacion'], name='clientes_cl_ultima__39af3d_idx')],
            },
        ),
    ]
