# Generated by Django 5.2.6 on 2026-05-28 18:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0001_initial'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='cliente',
            name='clientes_cl_rut_43a54a_idx',
        ),
    ]
