# Generated by Django 5.2.6 on 2025-11-21 00:25

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('productos', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cita',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_completo', models.CharField(max_length=200, verbose_name='Nombre Completo')),
                ('telefono', models.CharField(max_length=17, validators=[django.core.validators.RegexValidator(message="El número de teléfono debe estar en el formato: '+999999999'. Hasta 15 dígitos permitidos.", regex='^\\+?1?\\d{9,15}$')], verbose_name='Teléfono')),
                ('direccion', models.CharField(max_length=300, verbose_name='Dirección')),
                ('email', models.EmailField(max_length=254, verbose_name='Email')),
                ('tipo_reunion', models.CharField(choices=[('online', 'Online'), ('presencial', 'Presencial')], max_length=20, verbose_name='Tipo de Reunión')),
                ('fecha', models.DateField(verbose_name='Fecha de Reunión')),
                ('hora', models.TimeField(verbose_name='Hora de Reunión')),
                ('estado', models.CharField(choices=[('pendiente_aprobacion', 'Pendiente de Aprobación'), ('aprobada', 'Aprobada'), ('rechazada', 'Rechazada'), ('cancelada', 'Cancelada')], default='pendiente_aprobacion', max_length=25, verbose_name='Estado')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Creación')),
                ('fecha_aprobacion', models.DateTimeField(blank=True, null=True, verbose_name='Fecha de Aprobación')),
                ('admin_notas', models.TextField(blank=True, help_text='Razón de rechazo o notas internas', verbose_name='Notas del Administrador')),
            ],
            options={
                'verbose_name': 'Cita',
                'verbose_name_plural': 'Citas',
                'ordering': ['fecha', 'hora'],
            },
        ),
        migrations.CreateModel(
            name='Cotizacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_completo', models.CharField(max_length=200, verbose_name='Nombre Completo')),
                ('rut', models.CharField(blank=True, help_text='Formato: 12.345.678-9', max_length=12, verbose_name='RUT')),
                ('direccion', models.CharField(blank=True, max_length=300, verbose_name='Dirección')),
                ('email', models.EmailField(max_length=254, verbose_name='Email')),
                ('telefono', models.CharField(blank=True, max_length=17, verbose_name='Teléfono')),
                ('medidas_alto', models.DecimalField(decimal_places=2, help_text='Altura en centímetros', max_digits=6, verbose_name='Alto (cm)')),
                ('medidas_ancho', models.DecimalField(decimal_places=2, help_text='Ancho en centímetros', max_digits=6, verbose_name='Ancho (cm)')),
                ('medidas_profundidad', models.DecimalField(decimal_places=2, help_text='Profundidad en centímetros', max_digits=6, verbose_name='Profundidad (cm)')),
                ('material_preferido', models.CharField(choices=[('pino', 'Pino'), ('roble', 'Roble'), ('mdf', 'MDF'), ('melamina', 'Melamina'), ('otro', 'Otro')], max_length=20, verbose_name='Material Preferido')),
                ('descripcion_proyecto', models.TextField(blank=True, verbose_name='Descripción del Proyecto')),
                ('foto_lugar', models.ImageField(blank=True, help_text='Foto del espacio donde se instalará el mueble', null=True, upload_to='cotizaciones/fotos/', verbose_name='Foto del Lugar')),
                ('folio', models.CharField(blank=True, help_text='Número de folio único (ej: COT-001)', max_length=20, unique=True, verbose_name='Folio')),
                ('estado', models.CharField(choices=[('pendiente_aprobacion', 'Pendiente de Aprobación'), ('aprobada', 'Aprobada'), ('rechazada', 'Rechazada'), ('en_revision', 'En Revisión'), ('cotizada', 'Cotizada'), ('aceptada', 'Aceptada')], default='pendiente_aprobacion', max_length=25, verbose_name='Estado')),
                ('precio_cotizado', models.DecimalField(blank=True, decimal_places=0, help_text='Precio en pesos chilenos', max_digits=10, null=True, verbose_name='Precio Cotizado ($)')),
                ('admin_notas', models.TextField(blank=True, help_text='Notas internas, no visibles para el cliente', verbose_name='Notas Administrativas')),
                ('fecha_solicitud', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Solicitud')),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True, verbose_name='Última Actualización')),
                ('fecha_aprobacion', models.DateTimeField(blank=True, null=True, verbose_name='Fecha de Aprobación')),
                ('producto', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='productos.producto', verbose_name='Producto de Referencia')),
            ],
            options={
                'verbose_name': 'Cotización',
                'verbose_name_plural': 'Cotizaciones',
                'ordering': ['-fecha_solicitud'],
            },
        ),
        migrations.CreateModel(
            name='ConsentimientoLegal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('acepto_terminos', models.BooleanField(default=False, verbose_name='Aceptó Términos y Condiciones')),
                ('acepto_privacidad', models.BooleanField(default=False, verbose_name='Aceptó Política de Privacidad')),
                ('version_terminos', models.CharField(default='1.0', max_length=20, verbose_name='Versión de Términos y Condiciones')),
                ('version_privacidad', models.CharField(default='1.0', max_length=20, verbose_name='Versión de Política de Privacidad')),
                ('ip_address', models.GenericIPAddressField(help_text='IP desde donde se aceptaron los términos', verbose_name='Dirección IP')),
                ('user_agent', models.CharField(help_text='Navegador y sistema operativo del usuario', max_length=500, verbose_name='User Agent')),
                ('fecha_aceptacion', models.DateTimeField(auto_now_add=True, verbose_name='Fecha y Hora de Aceptación')),
                ('cita', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='consentimiento', to='cotizaciones.cita', verbose_name='Cita Relacionada')),
                ('cotizacion', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='consentimiento', to='cotizaciones.cotizacion', verbose_name='Cotización Relacionada')),
            ],
            options={
                'verbose_name': 'Consentimiento Legal',
                'verbose_name_plural': 'Consentimientos Legales',
                'ordering': ['-fecha_aceptacion'],
            },
        ),
    ]
