# Generated by Django 5.2.5 on 2025-11-22 13:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cotizaciones', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cita',
            name='meeting_link',
            field=models.URLField(blank=True, help_text='Link de Google Meet generado automáticamente para reuniones online', max_length=500, null=True, verbose_name='Link de Reunión Online'),
        ),
    ]
