# Generated by Django 5.2.5 on 2025-11-20 15:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cotizaciones', '0001_initial'),
        ('productos', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cotizacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_completo', models.CharField(max_length=200, verbose_name='Nombre Completo')),
                ('email', models.EmailField(max_length=254, verbose_name='Email')),
                ('telefono', models.CharField(max_length=17, verbose_name='Teléfono')),
                ('medidas_alto', models.DecimalField(decimal_places=2, help_text='Altura en centímetros', max_digits=6, verbose_name='Alto (cm)')),
                ('medidas_ancho', models.DecimalField(decimal_places=2, help_text='Ancho en centímetros', max_digits=6, verbose_name='Ancho (cm)')),
                ('medidas_profundidad', models.DecimalField(decimal_places=2, help_text='Profundidad en centímetros', max_digits=6, verbose_name='Profundidad (cm)')),
                ('material_preferido', models.CharField(choices=[('pino', 'Pino'), ('roble', 'Roble'), ('mdf', 'MDF'), ('melamina', 'Melamina'), ('otro', 'Otro')], max_length=20, verbose_name='Material Preferido')),
                ('descripcion_proyecto', models.TextField(verbose_name='Descripción del Proyecto')),
                ('estado', models.CharField(choices=[('pendiente', 'Pendiente'), ('en_revision', 'En Revisión'), ('cotizada', 'Cotizada'), ('aceptada', 'Aceptada'), ('rechazada', 'Rechazada')], default='pendiente', max_length=20, verbose_name='Estado')),
                ('precio_cotizado', models.DecimalField(blank=True, decimal_places=0, help_text='Precio en pesos chilenos', max_digits=10, null=True, verbose_name='Precio Cotizado ($)')),
                ('notas_admin', models.TextField(blank=True, help_text='Notas internas, no visibles para el cliente', verbose_name='Notas Administrativas')),
                ('fecha_solicitud', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Solicitud')),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True, verbose_name='Última Actualización')),
                ('producto', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='productos.producto', verbose_name='Producto de Referencia')),
            ],
            options={
                'verbose_name': 'Cotización',
                'verbose_name_plural': 'Cotizaciones',
                'ordering': ['-fecha_solicitud'],
            },
        ),
    ]
