# Generated by Django 5.2.5 on 2025-11-20 19:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cotizaciones', '0002_cotizacion'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConsentimientoLegal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('acepto_terminos', models.BooleanField(default=False, verbose_name='Aceptó Términos y Condiciones')),
                ('acepto_privacidad', models.BooleanField(default=False, verbose_name='Aceptó Política de Privacidad')),
                ('version_terminos', models.CharField(default='1.0', max_length=20, verbose_name='Versión de Términos y Condiciones')),
                ('version_privacidad', models.CharField(default='1.0', max_length=20, verbose_name='Versión de Política de Privacidad')),
                ('ip_address', models.GenericIPAddressField(help_text='IP desde donde se aceptaron los términos', verbose_name='Dirección IP')),
                ('user_agent', models.CharField(help_text='Navegador y sistema operativo del usuario', max_length=500, verbose_name='User Agent')),
                ('fecha_aceptacion', models.DateTimeField(auto_now_add=True, verbose_name='Fecha y Hora de Aceptación')),
                ('cita', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='consentimiento', to='cotizaciones.cita', verbose_name='Cita Relacionada')),
                ('cotizacion', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='consentimiento', to='cotizaciones.cotizacion', verbose_name='Cotización Relacionada')),
            ],
            options={
                'verbose_name': 'Consentimiento Legal',
                'verbose_name_plural': 'Consentimientos Legales',
                'ordering': ['-fecha_aceptacion'],
            },
        ),
    ]
