# Generated by Django 5.1.2 on 2025-11-22 22:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0001_initial'),
        ('cotizaciones', '0002_cita_meeting_link'),
    ]

    operations = [
        migrations.AddField(
            model_name='cotizacion',
            name='cliente',
            field=models.ForeignKey(blank=True, help_text='Vincular con un cliente registrado en el sistema', null=True, on_delete=django.db.models.deletion.SET_NULL, to='clientes.cliente', verbose_name='Cliente Habitual'),
        ),
    ]
