# Generated by Django 5.2.6 on 2026-05-28 18:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0002_remove_cliente_clientes_cl_rut_43a54a_idx'),
        ('cotizaciones', '0003_cotizacion_cliente'),
        ('productos', '0003_categoria_producto_categoria'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='cita',
            index=models.Index(fields=['fecha'], name='cotizacione_fecha_e8004f_idx'),
        ),
        migrations.AddIndex(
            model_name='cita',
            index=models.Index(fields=['hora'], name='cotizacione_hora_b420f0_idx'),
        ),
        migrations.AddIndex(
            model_name='cita',
            index=models.Index(fields=['estado'], name='cotizacione_estado_761760_idx'),
        ),
        migrations.AddIndex(
            model_name='cotizacion',
            index=models.Index(fields=['estado'], name='cotizacione_estado_468b01_idx'),
        ),
        migrations.AddIndex(
            model_name='cotizacion',
            index=models.Index(fields=['-fecha_solicitud'], name='cotizacione_fecha_s_65f218_idx'),
        ),
    ]
