# Generated by Django 5.2.6 on 2025-11-20 21:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cotizaciones', '0003_consentimientolegal'),
    ]

    operations = [
        migrations.AddField(
            model_name='cotizacion',
            name='direccion',
            field=models.CharField(blank=True, max_length=300, verbose_name='Dirección'),
        ),
        migrations.AddField(
            model_name='cotizacion',
            name='folio',
            field=models.CharField(blank=True, help_text='Número de folio único (ej: COT-001)', max_length=20, unique=True, verbose_name='Folio'),
        ),
        migrations.AddField(
            model_name='cotizacion',
            name='foto_lugar',
            field=models.ImageField(blank=True, help_text='Foto del espacio donde se instalará el mueble', null=True, upload_to='cotizaciones/fotos/', verbose_name='Foto del Lugar'),
        ),
        migrations.AddField(
            model_name='cotizacion',
            name='rut',
            field=models.CharField(blank=True, help_text='Formato: 12.345.678-9', max_length=12, verbose_name='RUT'),
        ),
        migrations.AlterField(
            model_name='cotizacion',
            name='descripcion_proyecto',
            field=models.TextField(blank=True, verbose_name='Descripción del Proyecto'),
        ),
        migrations.AlterField(
            model_name='cotizacion',
            name='telefono',
            field=models.CharField(blank=True, max_length=17, verbose_name='Teléfono'),
        ),
    ]
